import type { Command, CommandGroup, Registrable } from "./dispatch.ts";

const GENERATED_HEADER =
  "<!-- GENERATED by `bun run docs:cli` from the CLI command registry. DO NOT EDIT BY HAND. -->";

function isGroup(entry: Registrable): entry is CommandGroup {
  return "subcommands" in entry;
}

/** The invocation form shown for a command — its explicit `usage`, else derived. */
function usageOf(cmd: Command, prefix: string): string {
  return cmd.usage ?? `vesper ${prefix}${cmd.name}`;
}

/** Escape a cell value so a `|` in a summary cannot break the markdown table. */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

/**
 * Render the Markdown table of EVERY `vesper` command (one row per invocable leaf
 * command; group subcommands expanded). Pure + deterministic — shared by the
 * standalone reference and the README injection.
 */
export function renderCliTable(registry: readonly Registrable[]): string {
  const rows: string[] = [];
  for (const entry of registry) {
    if (isGroup(entry)) {
      for (const sub of entry.subcommands) {
        rows.push(`| \`${cell(usageOf(sub, `${entry.name} `))}\` | ${cell(sub.summary)} |`);
      }
    } else {
      rows.push(`| \`${cell(usageOf(entry, ""))}\` | ${cell(entry.summary)} |`);
    }
  }
  return ["| Command | Description |", "| --- | --- |", ...rows].join("\n");
}

/** The standalone `docs/CLI.md` reference (header + the full command table). */
export function renderCliDocs(registry: readonly Registrable[]): string {
  return `${[
    GENERATED_HEADER,
    "",
    "# Vesper CLI reference",
    "",
    "Every `vesper` command, generated from the command registry",
    "(`packages/vesper-cli/src/commands/index.ts`). Regenerate with `bun run docs:cli`.",
    "",
    renderCliTable(registry),
  ].join("\n")}\n`;
}

/** Markers delimiting the auto-injected command table in README.md. */
export const README_BEGIN = "<!-- BEGIN COMMANDS (auto-generated by `bun run docs:cli`) -->";
export const README_END = "<!-- END COMMANDS -->";

/**
 * Replace the marked command block in a README with the freshly-rendered table.
 * Returns the README unchanged if the markers are absent (so it's safe to run
 * anywhere). Pure — the caller does the file I/O.
 */
export function injectReadmeCommands(readme: string, registry: readonly Registrable[]): string {
  const start = readme.indexOf(README_BEGIN);
  const end = readme.indexOf(README_END);
  if (start === -1 || end === -1 || end < start) return readme;
  const block = `${README_BEGIN}\n\n${renderCliTable(registry)}\n\n${README_END}`;
  return readme.slice(0, start) + block + readme.slice(end + README_END.length);
}
