import type { Command, CommandGroup, Registrable } from "./dispatch.ts";

const GENERATED_HEADER =
  "<!-- GENERATED by `bun run docs:cli` from the CLI command registry. DO NOT EDIT BY HAND. -->";

function isGroup(entry: Registrable): entry is CommandGroup {
  return "subcommands" in entry;
}

/** The invocation form shown for a command — its explicit `usage`, else derived. */
function usageOf(cmd: Command, prefix: string): string {
  return cmd.usage ?? `vesper ${prefix}${cmd.name}`;
}

/** Escape a cell value so a `|` in a summary cannot break the markdown table. */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

/**
 * Render a Markdown reference of EVERY `vesper` command from the registry — one
 * row per invocable leaf command (group subcommands are expanded). Pure and
 * deterministic: the same registry always yields byte-identical output, so the
 * pre-commit guard can detect drift.
 */
export function renderCliDocs(registry: readonly Registrable[]): string {
  const rows: string[] = [];
  for (const entry of registry) {
    if (isGroup(entry)) {
      for (const sub of entry.subcommands) {
        rows.push(`| \`${cell(usageOf(sub, `${entry.name} `))}\` | ${cell(sub.summary)} |`);
      }
    } else {
      rows.push(`| \`${cell(usageOf(entry, ""))}\` | ${cell(entry.summary)} |`);
    }
  }

  return `${[
    GENERATED_HEADER,
    "",
    "# Vesper CLI reference",
    "",
    "Every `vesper` command, generated from the command registry",
    "(`packages/vesper-cli/src/commands/index.ts`). Regenerate with `bun run docs:cli`.",
    "",
    "| Command | Description |",
    "| --- | --- |",
    ...rows,
  ].join("\n")}\n`;
}
