#!/usr/bin/env bun
// Compiled daemon entrypoint for the desktop sidecar (DEV-112 Slice 2).
//
// `bun build --compile` bundles this into a single self-contained `vesper-daemon`
// binary that the Tauri shell spawns. Unlike `vesper daemon run` from source, the
// compiled binary has no `client/` directory and no runtime bundler (its FS is the
// virtual `/$bunfs`), so the UI server cannot build its assets on the fly. We instead
// embed the prebuilt client assets at COMPILE time via `with { type: "text" }` (inlined
// as string constants) and install them before the daemon starts.
//
// The `.txt` files are generated by `scripts/build-daemon.ts` immediately before the
// compile step; they do not exist in a normal source checkout (see text-imports.d.ts).
import { setEmbeddedClientAssets } from "@vesper/ui";
import { registry } from "./commands/index.ts";
import { dispatch } from "./dispatch.ts";
import appJs from "./generated/app-js.txt" with { type: "text" };
import indexHtml from "./generated/index-html.txt" with { type: "text" };

setEmbeddedClientAssets({ indexHtml, appJs });

// Default to `daemon run`; still forward any explicit argv the shell passes through.
const args = process.argv.slice(2);
process.exit(await dispatch(registry, args.length > 0 ? args : ["daemon", "run"]));
